blueprint:
  name: Friends of Hue 4 Button All functions (Corrected Long Press) 
  description: Automate your Friends of Hue 4 Button switch using Hue integration with short and long press. Be aware input.helper need to be created before automation works with corect long press
  domain: automation
  input:
    helper-remember-longrelease:
      name: Input.helper to remember longrelease
      description: A toggled helper, created through "settings - devices - helpers - create helpers". The helper can have whatever name
      selector:
        entity:
          domain: input_boolean

    hue-4-button-switch:
      name: Hue Frinds of 4-Button Switch
      description: Hue Frinds of 4-Button Switch
      selector:
        device:
          manufacturer: PhilipsFoH

    button_1_short_release:
      name: Short Release 1
      description: Action to run on button upper-left short release
      default: []
      selector:
        action: {}
    button_2_short_release:
      name: Short Release 2
      description: Action to run on button lower-left short release
      default: []
      selector:
        action: {}
    button_3_short_release:
      name: Short Release 3
      description: Action to run on button upper-right short release
      default: []
      selector:
        action: {}
    button_4_short_release:
      name: Short Release 4
      description: Action to run on button lower-right short release
      default: []
      selector:
        action: {}
        
    button_1_long_release:
      name: Long Release 1
      description: Action to run on button upper-left long release
      default: []
      selector:
        action: {}
    button_2_long_release:
      name: Long Release 2
      description: Action to run on button lower-left long release
      default: []
      selector:
        action: {}
    button_3_long_release:
      name: Long Release 3
      description: Action to run on button upper-right long release
      default: []
      selector:
        action: {}
    button_4_long_release:
      name: Long Release 4
      description: Action to run on button lower-right long release
      default: []
      selector:
        action: {}

    button_1_press:
      name: Press 1
      description: Action to run on button upper-left initial press
      default: []
      selector:
        action: {}
    button_2_press:
      name: Press 2
      description: Action to run on button lower-left initial press
      default: []
      selector:
        action: {}
    button_3_press:
      name: Press 3
      description: Action to run on button upper-right initial press
      default: []
      selector:
        action: {}
    button_4_press:
      name: Press 4
      description: Action to run on button lower-right initial press
      default: []
      selector:
        action: {}

    button_1_repeat:
      name: Repeat 1
      description: Action to run on button upper-left repeat
      default: []
      selector:
        action: {}
    button_2_repeat:
      name: Repeat 2
      description: Action to run on button lower-left repeat
      default: []
      selector:
        action: {}
    button_3_repeat:
      name: Repeat 3
      description: Action to run on button upper-right repeat
      default: []
      selector:
        action: {}
    button_4_repeat:
      name: Repeat 4
      description: Action to run on button lower-right repeat
      default: []
      selector:
        action: {}

mode: queued
max: 10

trigger:
- platform: event
  event_type: hue_event
  event_data:
    device_id: !input hue-4-button-switch
action:
- variables:
    type: '{{ trigger.event.data.type }}' 
    subtype: '{{ trigger.event.data.subtype }}'


- choose:
  - conditions: '{{ type == ''initial_press'' }}'
    sequence:
    - service: input_boolean.turn_on
      target:
        entity_id: !input 'helper-remember-longrelease'
    - choose:
      - conditions: '{{ subtype == 1 }}'
        sequence: !input 'button_1_press'
      - conditions: '{{ subtype == 2 }}'
        sequence: !input 'button_2_press'
      - conditions: '{{ subtype == 3 }}'
        sequence: !input 'button_3_press'  
      - conditions: '{{ subtype == 4 }}'
        sequence: !input 'button_4_press'

  - conditions: '{{ type == ''short_release'' }}'
    sequence:
    - choose:
      - conditions: 
          - condition: state
            entity_id: !input 'helper-remember-longrelease'
            state: "on"
        sequence: 
          - choose:
            - conditions: '{{ subtype == 1 }}'
              sequence: !input 'button_1_short_release'
            - conditions: '{{ subtype == 2 }}'
              sequence: !input 'button_2_short_release'
            - conditions: '{{ subtype == 3 }}'
              sequence: !input 'button_3_short_release'
            - conditions: '{{ subtype == 4 }}'
              sequence: !input 'button_4_short_release' 

  - conditions: '{{ type == ''repeat'' }}'
    sequence:
    - service: input_boolean.turn_off
      target:
        entity_id: !input 'helper-remember-longrelease'
    - choose:
      - conditions: '{{ subtype == 1 }}'
        sequence: !input 'button_1_repeat'
      - conditions: '{{ subtype == 2 }}'
        sequence: !input 'button_2_repeat'
      - conditions: '{{ subtype == 3 }}'
        sequence: !input 'button_3_repeat'
      - conditions: '{{ subtype == 4 }}'
        sequence: !input 'button_4_repeat'

  - conditions: '{{ type == ''long_release'' }}'
    sequence:
    - choose:
      - conditions: '{{ subtype == 1 }}'
        sequence: !input 'button_1_long_release'
      - conditions: '{{ subtype == 2 }}'
        sequence: !input 'button_2_long_release'
      - conditions: '{{ subtype == 3 }}'
        sequence: !input 'button_3_long_release'
      - conditions: '{{ subtype == 4 }}'
        sequence: !input 'button_4_long_release'
